config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/contact'
  get 'pages/about'
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    products = Product.all
    @product_first = products[0]
    @product_second = products[1]
    @product_third = products[2]
    @product_fourth = products[3]
  end

  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

    products = Product.all
    products_disliked = []

    @product_zero = products[0]
    @product_one = products[1]
    @product_two = products[2]
    @product_three = products[3]
    @product_four = products[4]
    @product_five = products[5]
    @product_six = products[6]
    @product_seven = products[7]
    @product_eight = products[8]
    @product_nine = products[9]

=begin
    products.each do |product|
      if products.include?(product) && !products_disliked.include?(product)
        @product_left = product
        break
      end
    end




    products.each do |product|
      if product != nil && @product_left != product
        @product_right = product
        break
      end
    end
=end

  end

  def show
    @product = Product.find(params[:id])
  end

  def select
    products = Product.all
    # get the first two elements from the array
    # if clicked on one product, the other one will be deleted from the array
    # get the next product from the array and compare it to the  product that was clicked on

    # count the clicks
    # after 10 clicks, show the product
    # decide whether to buy or to keep selecting
  end

  def article_params
    params.require(:product).permit(:name, :link, :colour, :photo, :price, :brand, :product_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">



  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->




</head>
<body>
  <%= render 'shared/navbar' %>
  <%= yield %>
  <%= render 'shared/footer' %>
  <%#= javascript_pack_tag 'application' %>
  <%#= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
</html>

app/views/pages/about.html.erb
<h1 style="margin-top: 50px;">This is the about page</h1>

app/views/pages/contact.html.erb
<h1 style="margin-top: 50px;">This is the contact page</h1>

app/views/pages/home.html.erb
<div id="small-banner">
  <h1>Shop the Fun way.</h1>
  <div class="banner-img">
    <p>Tester</p>
  </div>
</div>




<div class="how-it-works">
  <div style="width: 80%;">
    <h1>Here’s How It Works:</h1>
    <div class="container how-div">
      <div class="how-desc">
        <div>
          <h4>1. Use The Filter</h4>
          <p>Tell us about your item preferences and we'll customize your shopping experience.</p>
        </div>
      </div>
      <div class="how-pic">
        <%= render "use-filter.svg" %>
      </div>
    </div>
    <div class="container how-div">
      <div class="how-pic">
        <%= render "compare.svg" %>
      </div>
      <div class="how-desc-right">
        <div>
          <h4>2. Choose Your Preference</h4>
          <p>You'll be given two products to compare. Which one do you prefer?</p>
        </div>
      </div>
    </div>
    <div class="container how-div">
      <div class="how-desc">
        <div>
          <h4>3. Purchase The Item If You Like It</h4>
          <p>If you are not happy yet, just keep comparing it to other items until you found the right fit for you!</p>
        </div>
      </div>
      <div class="how-pic">
        <%= render "purchase-item.svg" %>
      </div>
    </div>
  </div>
</div>


<div class="start-btn-div">
  <%= link_to products_path do %>
  <div class="start-btn">
    <p>Lets get started</p>
  </div>
  <% end %>
</div>

<div class="with-you">
  <div class="with-you-txt">
    <h1>We're With You</h1>
    <p id="with-you-para">Online shopping should be fun and easy. Seeing many fashion items at once can stress us. So, we're trying to give you the fun shopping experience you were looking for to make your life easyier. Are you ready to try it?</p>
    <%= link_to products_path do %>
    <div class="start-btn-gnrl">
      <p>Let's try it</p>
    </div>
    <% end %>
  </div>
  <div class="with-you-img">
    <h1>placeholder</h1>
  </div>
</div>

<div class="most-popular-div">
  <h1>Our Most Popular Items</h1>
  <div class="most-popular">
    <div class="popular-element" style="background-image: url('<%= cl_image_path @product_first.photo.key, crop: :fill %>')">
      <h3>01</h3>
    </div>
    <div class="popular-element" style="background-image: url('<%= cl_image_path @product_second.photo.key, crop: :fill %>')">
      <h3>02</h3>
    </div>
    <div class="popular-element" style="background-image: url('<%= cl_image_path @product_third.photo.key, crop: :fill %>')">
      <h3>03</h3>
    </div>
    <div class="popular-element" style="background-image: url('<%= cl_image_path @product_fourth.photo.key, crop: :fill %>')">
      <h3>04</h3>
    </div>
  </div>
</div>

<div class="get-started">
  <h1>Are You Ready To Get Started?</h1>
  <%= link_to products_path do %>
  <div class="start-btn-gnrl">
    <p>Let's get started</p>
  </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="product-compare-display">


  <div class="product-comp-inner">
    <div class="left-product" id="prod-one" style="background-image: url('<%= cl_image_path @product_zero.photo.key, crop: :fill %>')">
      <i class="fas fa-thumbs-down like"></i>
      <p>left</p>
      <div class="buy-product">
        <%= link_to product_path(@product_zero) do%>
        <div style="display: flex; align-items: center; justify-content: center; height: 100%">
          <h5>Show Details</h5>
        </div>
        <% end %>
      </div>
    </div>


    <div class="right-product" id="prod-two" style="background-image: url('<%= cl_image_path @product_one.photo.key, crop: :fill %>')">
      <i class="fas fa-thumbs-down like"></i>
      <p>right</p>
      <div class="buy-product">
        <%= link_to product_path(@product_one) do%>
        <div style="display: flex; align-items: center; justify-content: center; height: 100%">
          <h5>Show Details</h5>
        </div>
        <% end %>
      </div>
    </div>

    <div class="left-product" id="prod-three" style="background-image: url('<%= cl_image_path @product_two.photo.key, crop: :fill %>')">
      <i class="fas fa-thumbs-down like"></i>
      <p>left</p>
      <div class="buy-product">
        <%= link_to product_path(@product_two) do%>
        <div style="display: flex; align-items: center; justify-content: center; height: 100%">
          <h5>Show Details</h5>
        </div>
        <% end %>
      </div>
    </div>


    <div class="right-product" id="prod-four" style="background-image: url('<%= cl_image_path @product_three.photo.key, crop: :fill %>')">
      <i class="fas fa-thumbs-down like"></i>
      <p>right</p>
      <div class="buy-product">
        <%= link_to product_path(@product_three) do%>
        <div style="display: flex; align-items: center; justify-content: center; height: 100%">
          <h5>Show Details</h5>
        </div>
        <% end %>
      </div>
    </div>



    <div class="left-product" id="prod-five" style="background-image: url('<%= cl_image_path @product_four.photo.key, crop: :fill %>')">
      <i class="fas fa-thumbs-down like"></i>
      <p>left</p>
      <div class="buy-product">
        <%= link_to product_path(@product_four) do%>
        <div style="display: flex; align-items: center; justify-content: center; height: 100%">
          <h5>Show Details</h5>
        </div>
        <% end %>
      </div>
    </div>


    <div class="right-product" id="prod-six" style="background-image: url('<%= cl_image_path @product_five.photo.key, crop: :fill %>')">
      <i class="fas fa-thumbs-down like"></i>
      <p>right</p>
      <div class="buy-product">
        <%= link_to product_path(@product_five) do%>
        <div style="display: flex; align-items: center; justify-content: center; height: 100%">
          <h5>Show Details</h5>
        </div>
        <% end %>
      </div>
    </div>

    <div class="left-product" id="prod-seven" style="background-image: url('<%= cl_image_path @product_six.photo.key, crop: :fill %>')">
      <i class="fas fa-thumbs-down like"></i>
      <p>left</p>
      <div class="buy-product">
        <%= link_to product_path(@product_six) do%>
        <div style="display: flex; align-items: center; justify-content: center; height: 100%">
          <h5>Show Details</h5>
        </div>
        <% end %>
      </div>
    </div>


    <div class="right-product" id="prod-eight" style="background-image: url('<%= cl_image_path @product_seven.photo.key, crop: :fill %>')">
      <i class="fas fa-thumbs-down like"></i>
      <p>right</p>
      <div class="buy-product">
        <%= link_to product_path(@product_seven) do%>
        <div style="display: flex; align-items: center; justify-content: center; height: 100%">
          <h5>Show Details</h5>
        </div>
        <% end %>
      </div>
    </div>




    <div class="dont-like" id="last-option">
      <h1>You still don't like the product?</h1>
      <%= link_to products_path do %>
      <div class="start-btn-gnrl">
        <p>No, keep choosing</p>
      </div>
      <% end %>
    </div>


  </div>
</div>


<script type="text/javascript">
  var elementOne = document.getElementById("prod-one");
  var elementTwo = document.getElementById("prod-two");
  var elementThree = document.getElementById("prod-three");
  var elementFour = document.getElementById("prod-four");
  var elementfive = document.getElementById("prod-five");
  var elementsix = document.getElementById("prod-six");
  var elementseven = document.getElementById("prod-seven");
  var elementeight = document.getElementById("prod-eight");
  var lastOption = document.getElementById("last-option");

  var arr = [];

  arr.push(elementOne);
  arr.push(elementTwo);
  arr.push(elementThree);
  arr.push(elementFour);
  arr.push(elementfive);
  arr.push(elementsix);
  arr.push(elementseven);
  arr.push(elementeight);

  elementOne.addEventListener("click", function(){
    elementOne.style.visibility = "hidden";
    myFunction();
    myFunctionTwo()
  });

  elementTwo.addEventListener("click", function(){
    elementTwo.style.visibility = "hidden"
    myFunction();
    myFunctionTwo()
  });

  elementThree.addEventListener("click", function(){
    elementThree.style.visibility = "hidden";
    myFunction();
    myFunctionTwo()
  });

  elementFour.addEventListener("click", function(){
    elementFour.style.visibility = "hidden";
    myFunction();
    myFunctionTwo()
  });

  elementfive.addEventListener("click", function(){
    elementfive.style.visibility = "hidden";
    myFunction();
    myFunctionTwo()
  });

  elementsix.addEventListener("click", function(){
    elementsix.style.visibility = "hidden"
    myFunction();
    myFunctionTwo()
  });

  elementseven.addEventListener("click", function(){
    elementseven.style.visibility = "hidden";
    myFunction();
    myFunctionTwo()
  });

  elementeight.addEventListener("click", function(){
    elementeight.style.visibility = "hidden";
    myFunction();
    myFunctionTwo()
  });


  function myFunction() {
    var counter = 0;
    for (i = 0; i < arr.length; i++) {
      if (arr[i].style.visibility == "hidden") {
        counter++;
      }
    }

    if (counter == arr.length - 1) {
      for (i = 0; i < arr.length; i++) {
        if (!(arr[i].style.visibility == "hidden")) {
          //arr[i].style.left = "45px";

          arr[i].style.left ="0";
          arr[i].style.right ="0";
          arr[i].style.marginLeft ="auto";
          arr[i].style.marginRight ="auto";
          //arr[i].style.width ="";
          //arr[i].style.height ="100%";



          //alert("We found your product!");
          //lastOption.style.visibility = "visible";
        }
      }
    }
  }

  function myFunctionTwo() {
    var counter = 0;
    for (i = 0; i < arr.length; i++) {
      if (arr[i].style.visibility == "hidden") {
        counter++;
      }
    }

    if (counter == arr.length) {
      lastOption.style.visibility = "visible";
    }
  }



</script>

app/views/products/show.html.erb
<div class="product-display">
  <div class="inner-product-display">
    <div id="image" style="background-image: url('<%= cl_image_path @product.photo.key, crop: :fill %>')">
      <h1>Test</h1>
    </div>
    <div class="product-desc">
      <h5>Product Name: <%= @product.name %></h5>
      <h5>Product Type: <%= @product.product_type %></h5>
      <h5>Colour: <%= @product.colour %></h5>
      <h5>Brand: <%= @product.brand %></h5>
      <div class="show-buttons">
        <a class="start-btn-gnrl" href="/products">Keep Comparing</a>
        <a class="start-btn-gnrl-two" href="<%= @product.link %>">Buy Product</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
    <div style="height: 100%" class="container">
      <div class="footer-content">
        <div class="footer-logo footer-part">
          <h3>SelectFit</h3>
        </div>
        <div class="footer-part">
          <h5>Most Popular Brands</h5>
          <ul>
            <li>Adidas Originals</li>
            <li>Champion</li>
            <li>Comme des Garçons</li>
            <li>Nike</li>
            <li>Off-White</li>
            <li>Polo Ralph Lauren</li>
          </ul>
        </div>
        <div class="footer-part">
          <h5>Contact us</h5>
          <ul>
            <li>+49 111111111</li>
            <li>hello@selectfit.com</li>
          </ul>
        </div>
        <div class="footer-part">
          <h5>Follow us</h5>
          <div class="social-media-flex">
            <i class="fab fa-facebook-square"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-twitter"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="nav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to root_path do %>
  <div style="padding-right: 21px;" class="nav-bar-logo">
    <h3 id="nav-logo">SelectFit</h3>
  </div>
  <% end %>

  <div class="navbar-right">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", "/pages/about", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", "/pages/contact", class: "nav-link" %>
        </li>
        <li class="nav-item start-btn-navbar">
          <%= link_to products_path do %>
          <div class="start-btn-navbar">
            <p>Shop</p>
          </div>
          <% end %>
          <%#= link_to "Shop", products_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</div>